spring.application.name=recipies

#Configuarion de la base de dato PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/recipesplan
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
